version: "3.8"

services:
  anvil:
    container_name: aetherisnova_anvil
    entrypoint: anvil --block-time 1 --block-base-fee-per-gas 0 --gas-limit 3000000000 --hardfork cancun --host 0.0.0.0
    healthcheck:
      test: [ "CMD-SHELL", "anvil --help || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/amd64
    ports:
      - "8545:8545"
