packages:
  - packages/*

catalog:
  "@aetherisnova/errors": ^1.0.0
  "@aetherisnova/types": ^1.2.0
  "@aetherisnova/ui-components": ^1.2.0-beta.1
  "@aetherisnova/utils": ^1.2.0
  "@eslint/js": ^9.18.0
  "@stablelib/base64": ^2.0.0
  "@stablelib/utf8": ^2.0.0
  "@types/node": ^22.10.1
  "@wagmi/cli": ^2.2.0
  "@wagmi/connectors": ^5.7.5
  "@wagmi/core": ^2.x
  chalk: ^5.3.0
  concurrently: ^9.1.0
  dotenv: ^16.4.7
  eslint: ^9.16.0
  eslint-config-prettier: ^9.1.0
  globals: ^15.13.0
  prettier: ^3.4.2
  prettier-plugin-solidity: ^1.4.1
  solhint: ^5.0.3
  shx: ^0.3.4
  tsx: 4.19.2
  typescript: ^5.7.2
  typescript-eslint: ^8.18.0
  viem: 2.x
  vite: ^6.0.3
  vite-plugin-dts: ^4.3.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^2.1.8
