export const NOT_ELIGIBLE_TO_SUBMIT_PROPOSAL = 'NOT_ELIGIBLE_TO_SUBMIT_PROPOSAL';
export const RECIPIENT_ALREADY_HAS_TOKEN = 'RECIPIENT_ALREADY_HAS_TOKEN';
export const TITLE_TOO_LONG = 'TITLE_TOO_LONG';
export const TOKEN_DOES_NOT_EXIST = 'TOKEN_DOES_NOT_EXIST';
export const TOKEN_NOT_ELIGIBLE = 'TOKEN_NOT_ELIGIBLE';
