[profile.default]
allow_paths = ["../arbiter", "../sigillum"]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
libs = ["dependencies"]
optimizer = true
out = "dist/contracts"
solc = "0.8.24"
src = "src/contracts"
test = "test/contracts"
viaIR = true

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.1.0"
solmate = "6.8.0"
