[profile.default]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
libs = ["lib"]
out = "out"
solc = "0.8.24"
src = "src"

[profile.local]
eth_rpc_url = "http://127.0.0.1:8546" # local anvil instance
