name: "Release"

on:
  push:
    branches:
      - beta
      - main

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  packages: write  # to be able to publish packages
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release_icons:
    name: "Release - @aetherisnova/sigillum"
    uses: ./.github/workflows/default_release.yml
    with:
      package_dir: "sigillum"
