name: "Release"

on:
  push:
    branches:
      - beta
      - main

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true # ensure only one release workflow runs per branch (e.g., "release-beta" or "release-main")

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  packages: write  # to be able to publish packages
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release_types:
    name: "Release - _types"
    uses: ./.github/workflows/internal_release.yml
    with:
      package_dir: "_types"

  release_utils:
    needs: [release_types]
    name: "Release - _utils"
    uses: ./.github/workflows/internal_release.yml
    with:
      package_dir: "_utils"

  release_arbiter:
    needs: [release_types, release_utils]
    name: "Release - @aetherisnova/arbiter"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "arbiter"
      package_name: "@aetherisnova/arbiter"
      with_foundry: true

  release_sigillum:
    needs: [release_types, release_utils, release_arbiter]
    name: "Release - @aetherisnova/sigillum"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "sigillum"
      package_name: "@aetherisnova/sigillum"
      with_foundry: true
