name: "Release"

on:
  push:
    branches:
      - beta
      - main

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  packages: write  # to be able to publish packages
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release_types:
    name: "Release - _types"
    uses: ./.github/workflows/internal_release.yml
    with:
      package_dir: "_types"

  release_utils:
    needs: [release_types]
    name: "Release - _utils"
    uses: ./.github/workflows/internal_release.yml
    with:
      package_dir: "_utils"

  release_regimen:
    needs: [release_types, release_utils]
    name: "Release - @aetherisnova/regimen"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "regimen"
      package_name: "@aetherisnova/regimen"
      with_foundry: true

  release_sigillum:
    needs: [release_types, release_utils, release_regimen]
    name: "Release - @aetherisnova/sigillum"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "sigillum"
      package_name: "@aetherisnova/sigillum"
      with_foundry: true
